sources:
  - .

reports:
  html: ./build/report
  markdown: ./build/report.md

requirements:
  fail_on_error: true
  rules:
    cyclomatic_complexity:
      max: 1000
      exclude: 
        - "Reporter.php"

    loc:
      max: 100
      exclude: []

    coupling:
      forbidden:
        - from: "Model"
          to: "Controller"
