sources:
  - ./internal
exclude: []
reports:
  html: ./build/report
  markdown: ./build/report.md
requirements:
  rules:
    architecture:
      coupling:
        forbidden:
          - from: Application
            to: Hal
    volume:
      loc:
        max: 150
        min: 0
        exclude: []
  fail_on_error: true
