
src: ./src
exclude: []
anomaly:
  threshold:

    # The threshold for the average of the metrics
    average:
      method:
        lines_of_code: 10
      project:
        cyclomatic_complexity: 5
        lines_of_code: 5

    # The threshold for the maximum reached by the metrics
    total:
      class:
        cyclomatic_complexity: 100
        lines_of_code: 100
      project:
        cyclomatic_complexity: 50
        lines_of_code: 50
