project_name: ast-metrics

before:
  hooks:
    - go mod tidy

builds:
  - id: ast-metrics
    main: ./cmd/ast-metrics
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    builds:
      - ast-metrics
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Date "20060102_150405" }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: Halleck45
    name: ast-metrics
  draft: false
  prerelease: false

changelog:
  sort: asc
  use: github
