version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: app
    env: ["CGO_ENABLED=1"]
    goos: [__GOOS__]
    goarch: [__GOARCH__]
    ldflags: ["-s", "-w"]
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
