package classifier

// ClassificationLabels contains all possible classification labels.
// This file is auto-generated from labels/c4.csv - DO NOT EDIT MANUALLY.
// To regenerate: python3 ai/training/classifier/v3/6-generate-labels.py

var ClassificationLabels = map[int]string{
	1: "component:interface:controller",
	2: "component:interface:presenter",
	3: "component:interface:view",
	4: "component:interface:view_model",
	5: "component:app:use_case",
	6: "component:app:service",
	7: "component:app:flow_orchestrator",
	8: "component:app:transaction_manager",
	9: "component:app:mapper",
	10: "component:app:converter",
	11: "component:domain:entity",
	12: "component:domain:value_object",
	13: "component:domain:aggregate_root",
	14: "component:domain:service",
	15: "component:domain:rule",
	16: "component:domain:policy",
	17: "component:domain:specification",
	18: "component:data_access:repository",
	19: "component:data_access:gateway",
	20: "component:data_access:mapper",
	21: "component:data_access:dto",
	22: "component:messaging:handler",
	23: "component:messaging:publisher",
	24: "component:messaging:subscriber",
	25: "component:messaging:bus",
	26: "construction:factory:abstract",
	27: "construction:factory:method",
	28: "construction:builder:fluent",
	29: "construction:builder:configurator",
	30: "construction:adapter:external",
	31: "construction:adapter:internal",
	32: "construction:transformer:data",
	33: "construction:transformer:view",
	34: "infrastructure:client:http",
	35: "infrastructure:client:database",
	36: "infrastructure:client:queue",
	37: "infrastructure:system:file_io",
	38: "infrastructure:system:environment",
	39: "infrastructure:logging:logger",
	40: "infrastructure:monitoring:metric",
	41: "infrastructure:security:token_handler",
	42: "infrastructure:security:authenticator",
	43: "infrastructure:security:authorizer",
	44: "infrastructure:cache:manager",
	45: "infrastructure:configuration:loader",
	46: "infrastructure:configuration:model",
	47: "infrastructure:error:handler",
	48: "component:core:library",
	49: "component:core:algorithm",
	50: "component:core:utility",
	51: "component:core:runtime_support",
	52: "utility:helper:string",
	53: "utility:helper:date_time",
	54: "utility:helper:math",
	55: "utility:helper:component",
	56: "utility:converter:format",
	57: "utility:validator:input",
	58: "utility:validator:model",
	59: "utility:serialization:serializer",
	60: "utility:serialization:deserializer",
	61: "framework:internal:infrastructure",
	62: "development:test:case",
	63: "development:test:fixture",
	64: "development:test:mock",
}

// ClassificationDescriptions contains descriptions for each classification label.
var ClassificationDescriptions = map[string]string{
	"component:interface:controller": "Entry point for external requests (Web/API/CLI).",
	"component:interface:presenter": "Prepares data for display (MVP/MVVM).",
	"component:interface:view": "User interface representation.",
	"component:interface:view_model": "View-specific data model.",
	"component:app:use_case": "Single business use case (Clean/Hexagonal).",
	"component:app:service": "Application service coordinating multiple components.",
	"component:app:flow_orchestrator": "Orchestrates a sequence of multi-step processes.",
	"component:app:transaction_manager": "Unitary and transactional management of operations.",
	"component:app:mapper": "Conversion between models (Domain/DTO/Infra).",
	"component:app:converter": "Multi-format conversion or data restructuring.",
	"component:domain:entity": "Business entity.",
	"component:domain:value_object": "Business value object.",
	"component:domain:aggregate_root": "Entry point of a business aggregate.",
	"component:domain:service": "Business service without technical dependencies.",
	"component:domain:rule": "Simple encapsulated business rule.",
	"component:domain:policy": "Structuring business policy (multi-rules).",
	"component:domain:specification": "Complex boolean business specification.",
	"component:data_access:repository": "Abstraction for entity access.",
	"component:data_access:gateway": "Exit point to an external service.",
	"component:data_access:mapper": "Domain <-> Persistence/Transport conversion.",
	"component:data_access:dto": "Transfer object without business logic.",
	"component:messaging:handler": "Processes an incoming message/command/event.",
	"component:messaging:publisher": "Emits messages/events.",
	"component:messaging:subscriber": "Listens to external events.",
	"component:messaging:bus": "Routing bus (commands/requests/events).",
	"construction:factory:abstract": "Interface for object families.",
	"construction:factory:method": "Static method or class for instantiation.",
	"construction:builder:fluent": "Progressive construction of complex objects.",
	"construction:builder:configurator": "Adding configurations after construction.",
	"construction:adapter:external": "Adapter to external interface.",
	"construction:adapter:internal": "Adapter between internal components.",
	"construction:transformer:data": "Structural data conversion.",
	"construction:transformer:view": "Data transformation for display.",
	"infrastructure:client:http": "Wrapper for HTTP calls.",
	"infrastructure:client:database": "Database driver/connection wrapper.",
	"infrastructure:client:queue": "Message queue client (Kafka/RabbitMQ).",
	"infrastructure:system:file_io": "File access.",
	"infrastructure:system:environment": "Environment variable access.",
	"infrastructure:logging:logger": "Logging.",
	"infrastructure:monitoring:metric": "Metric collection.",
	"infrastructure:security:token_handler": "Token management.",
	"infrastructure:security:authenticator": "Identity verification.",
	"infrastructure:security:authorizer": "Permission verification.",
	"infrastructure:cache:manager": "Cache management.",
	"infrastructure:configuration:loader": "Configuration file loading.",
	"infrastructure:configuration:model": "Typed configuration model.",
	"infrastructure:error:handler": "Centralized error handling.",
	"component:core:library": "Low-level generic code",
	"component:core:algorithm": "Algorithm or data structure implementation.",
	"component:core:utility": "Generic internal non-business tools.",
	"component:core:runtime_support": "Components related to low-level operation (threads",
	"utility:helper:string": "String helpers.",
	"utility:helper:date_time": "Date/time helpers.",
	"utility:helper:math": "Math helpers.",
	"utility:helper:component": "Component utilities.",
	"utility:converter:format": "Format conversions (XML/JSON/etc.).",
	"utility:validator:input": "Raw data validation.",
	"utility:validator:model": "Domain integrity validation.",
	"utility:serialization:serializer": "Object serialization.",
	"utility:serialization:deserializer": "Object deserialization.",
	"framework:internal:infrastructure": "Internal code provided by a framework.",
	"development:test:case": "Unit/integration test class.",
	"development:test:fixture": "Test data/state.",
	"development:test:mock": "Simulated object for isolation.",
}

// GetLabel returns the label for a given line number (1-indexed).
func GetLabel(lineNumber int) string {
	if label, ok := ClassificationLabels[lineNumber]; ok {
		return label
	}
	return ""
}

// GetDescription returns the description for a given label.
func GetDescription(label string) string {
	if description, ok := ClassificationDescriptions[label]; ok {
		return description
	}
	return ""
}
