name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Fetch tags
      - run: git fetch --force --tags

      # Install dependencies
      - uses: php-actions/composer@v6
        with:
          dev: no
          php_version: "8.1"
          args: "--working-dir=src/Php/phpsources --optimize-autoloader"

      # Commit changes
      - name: "Commit changes"
        run: |
            git config --local user.email "bot@ast-metrics.org"
            git config --local user.name "AST Metrics Bot"
            git add .
            git commit -m "chore: update dependencies"
            git tag -a -m "chore: update dependencies" "v$(date +'%Y%m%d%H%M%S')"

      # Install go dependencies
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # run tests
      - name: "Test application"
        run: go test

      # Build artifacts
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
