name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

  workflow_dispatch:


permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install go dependencies
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # Zig (for C dependencies, like libgit)
      - uses: goto-bus-stop/setup-zig@v2

      - name: Set output
        id: macos_sdk
        run: echo "path=$(xcrun --show-sdk-path)" >> $GITHUB_OUTPUT

      # run tests
      - name: "Test application"
        run: go test

      # Build artifacts
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          SDK_PATH: ${{ steps.macos_sdk.outputs.path }}